"""Return advisory rules that shape agent-friendly Julia APIs."""
julia_agent_policy_rules() = [
    JuliaHarnessRule(
        AGENT_JL_R001,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public API lacks an intent doc",
        "Document exported or public Julia API with a JuliaSyntax docstring so agents can reason from native syntax without guessing intent.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R002,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public method has a broad positional surface",
        "Prefer keyword options or a named config object when exported Julia methods need many arguments.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R003,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public method exposes positional Bool flags",
        "Prefer keyword Bool options or a named config object when exported Julia methods need multiple flags.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R004,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public method exposes a stringly domain argument",
        "Prefer a named domain carrier when exported Julia methods accept stringly state, mode, kind, phase, status, tag, or type arguments.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R005,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public API name spans multiple owners",
        "Keep exported Julia API names owned by one file or document a deliberate extension pattern when a public method family spans owners.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R006,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Module owner fans out without an intent doc",
        "Document module owner files that fan out to many local include owners so agents can understand the aggregation boundary.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R007,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public method hides deep control flow",
        "Prefer named pipeline steps when exported Julia methods hide algorithm shape behind deeply nested control flow.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R008,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public method body lacks named pipeline steps",
        "Split broad exported Julia methods into named pipeline steps when the public body has many top-level statements.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R009,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public method family is scattered across owners",
        "Document an explicit Julia dispatch or extension pattern when an exported method family is implemented across multiple owner files.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R010,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Macro-heavy public API lacks a syntax contract",
        "Document macro-heavy exported Julia methods with a syntax, macro expansion, or generated-code contract so agents can preserve parser-visible behavior.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R011,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public type has untyped fields",
        "Give exported Julia struct fields explicit type annotations so agents can understand public data shape without inferring `Any` from implementation details.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R012,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public type exposes stringly domain fields",
        "Prefer Symbol, enum, or named value carriers when exported Julia structs expose mode, status, category, or type fields.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R013,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public mutable type lacks a mutation contract",
        "Document mutation ownership, lifecycle, or invariants when exported Julia types are mutable.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R014,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Pkg.test lacks the harness verification profile",
        "Projects that depend on JuliaLangProjectHarness should mount `assert_julia_project_harness_test_profile_clean` inside package tests so agents receive policy, search, and verification feedback during `Pkg.test`.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R015,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Internal method nests traversal scaffolding",
        "Extract internal traversal bodies with nested loops and guard branches into named iterators, predicates, or data-processing helpers so agents can repair algorithm steps without untangling scaffolding.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R016,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public mutating method lacks a mutation contract",
        "Document which arguments or state are mutated when exported Julia methods use the `!` mutating-name convention.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R017,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Unsafe construct lacks an evidence contract",
        "Document a concrete safety or performance reason and focused verification evidence when non-test Julia code uses `eval`, `ccall`, external process execution, `@eval`, or `@inbounds`.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R018,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public generic API lacks type coverage",
        "Exercise exported Julia methods with explicit `where` type parameters against more than one relevant input type when the API claims generic behavior.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R019,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Documenter docs lack public API doctests",
        "When a Julia package uses Documenter, document exported/public API with executable `jldoctest`, `@example`, or `@repl` examples instead of prose-only references.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R020,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Stringly branch dispatch lacks a typed domain model",
        "When exported Julia methods branch over stringly domains, prefer a typed carrier; if Moshi ADTs or pattern matching are chosen, keep Moshi optional through `[weakdeps]` and `[extensions]` unless it is core API.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R021,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "External method extension risks type piracy",
        "Extending an external Julia function should dispatch on at least one package-owned type, or carry a concrete interop/type-piracy contract for why the foreign-function/foreign-type method is intentional.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R022,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Moshi domain model lacks a match bridge",
        "When Moshi `@data` covers a stringly branch domain, add parser-visible `@match` cases or typed methods so agents see how the real project logic uses the domain model.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R023,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public return annotation lacks a contract",
        "Document concrete return annotations on exported Julia methods so agents do not add narrow runtime assertions without understanding the API contract.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R024,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Package source owns mutable global state",
        "Avoid non-const mutable global bindings in package source; prefer explicit state objects, const handles with reset contracts, or dependency-injected caches.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R025,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public type has broadly abstract fields",
        "Avoid `Any`, `Function`, and broad abstract field annotations in exported Julia structs; prefer concrete fields or type parameters that preserve the public data contract.",
        labels("agent-policy"),
    ),
    JuliaHarnessRule(
        AGENT_JL_R026,
        JULIA_AGENT_POLICY_PACK_ID,
        Info,
        "Public failure path lacks a contract",
        "Document failure, exception, assertion, or precondition behavior when exported Julia methods throw errors or use parser-visible assertions.",
        labels("agent-policy"),
    ),
]
