"""JuliaSyntax-native project harness for Julia package policy and agent context."""
module JuliaLangProjectHarness

include("model.jl")
include("parser.jl")
include("rules.jl")
include("render.jl")
include("runner.jl")
include("search_index.jl")
include("search_index/owners.jl")
include("search_index/types.jl")
include("search_index/functions.jl")
include("search_index/moshi.jl")
include("search_render.jl")
include("agent_snapshot.jl")
include("verification.jl")
include("verification/extensions.jl")
include("verification/responsibility_inference.jl")
include("verification/contracts.jl")
include("verification/receipt_templates.jl")
include("verification/receipts.jl")
include("verification/advice.jl")
include("verification/profile_index.jl")
include("moshi_extension.jl")
include("cli.jl")

export JuliaDiagnosticSeverity,
    JuliaHarnessConfig,
    JuliaHarnessFinding,
    JuliaHarnessReport,
    JuliaHarnessRule,
    JuliaFileReport,
    JuliaSearchIndexEntry,
    JuliaSearchResult,
    JuliaVerificationProfileCandidate,
    JuliaVerificationProfileIndex,
    JuliaVerificationReceiptReview,
    JuliaVerificationTaskIndex,
    JuliaVerificationTaskRecord,
    JuliaVerificationProfile,
    RulePackDescriptor,
    SourceLocation,
    assert_julia_lang_harness_clean,
    assert_julia_project_harness_clean,
    assert_julia_project_harness_pkg_test_clean,
    assert_julia_project_harness_test_profile_clean,
    assert_julia_verification_receipts_accepted,
    build_julia_project_verification_profile,
    build_julia_verification_profile_index,
    build_julia_verification_task_index,
    default_julia_harness_config,
    julia_agent_policy_rules,
    julia_modularity_rules,
    julia_project_policy_rules,
    julia_project_search_index,
    julia_rule_pack_descriptors,
    julia_syntax_rules,
    julia_lang_search_index,
    moshi_extension_capabilities,
    read_julia_verification_receipts_json,
    render_julia_project_harness,
    render_julia_project_harness_advice,
    render_julia_project_harness_agent_snapshot,
    render_julia_project_harness_json,
    render_julia_search_results,
    render_julia_verification_pending_advice,
    render_julia_verification_profile,
    render_julia_verification_profile_index,
    render_julia_verification_profile_index_json,
    render_julia_verification_profile_json,
    render_julia_verification_receipt_template,
    render_julia_verification_receipt_reviews,
    render_julia_verification_receipt_reviews_json,
    render_julia_verification_task_index,
    render_julia_verification_task_index_json,
    review_julia_verification_receipts,
    run_julia_project_harness_cli,
    run_julia_lang_harness,
    run_julia_project_harness,
    search_julia_index,
    search_julia_lang,
    search_julia_project

end
