using Pkg

include("rules/catalog.jl")
include("rules/agent_catalog.jl")
include("rules/common.jl")
include("rules/project_policy.jl")
include("rules/extensions.jl")
include("rules/test_targets.jl")
include("rules/modularity.jl")
include("rules/agent_policy.jl")
include("rules/agent_policy/test_profile.jl")
include("rules/agent_policy/mutation_contracts.jl")
include("rules/agent_policy/unsafe_constructs.jl")
include("rules/agent_policy/type_coverage.jl")
include("rules/evaluation.jl")
